In [9]:
import numpy as np

In [61]:
'''Input:
Values (stored in array v)
Weights (stored in array w)
Number of distinct items (n)
Knapsack capacity (W) 
'''

c = 30
n = 10
w = (np.random.rand(n) * 10).astype(int)
v = (np.random.rand(n) * 10).astype(int)
print(w)
print(v)
m = np.zeros((n, c))
optimal_set = []



for i in range(n):
    for j in range(c):
        if w[i] > j:
            m[i, j] = m[i-1, j]
        else:
            m[i, j] = max(m[i-1, j], m[i-1, j-w[i]] + v[i])
            if(m[i-1, j-w[i]] + v[i] > m[i-1, j]):
                optimal_set.append(i)

print(m)

print("optimal set:")
optimal_set

[1 7 7 1 8 7 3 5 9 1]
[9 4 4 5 8 7 0 3 3 1]
[[  0.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.
    9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.   9.
    9.   9.   0.]
 [  0.   9.   9.   9.   9.   9.   9.   9.  13.  13.  13.  13.  13.  13.
   13.  13.  13.  13.  13.  13.  13.  13.  13.  13.  13.  13.  13.  13.
   13.  13.   0.]
 [  0.   9.   9.   9.   9.   9.   9.   9.  13.  13.  13.  13.  13.  13.
   13.  17.  17.  17.  17.  17.  17.  17.  17.  17.  17.  17.  17.  17.
   17.  17.   0.]
 [  0.   9.  14.  14.  14.  14.  14.  14.  14.  18.  18.  18.  18.  18.
   18.  18.  22.  22.  22.  22.  22.  22.  22.  22.  22.  22.  22.  22.
   22.  22.   0.]
 [  0.   9.  14.  14.  14.  14.  14.  14.  14.  18.  22.  22.  22.  22.
   22.  22.  22.  26.  26.  26.  26.  26.  26.  26.  30.  30.  30.  30.
   30.  30.   0.]
 [  0.   9.  14.  14.  14.  14.  14.  14.  16.  21.  22.  22.  22.  22.
   22.  22.  25.  29.  29.  29.  29.  29.  29.  29.  33.  33.  33.  33.
  

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9,
 9]

In [64]:
def solve(items, capacity):

    # print optimal_value
    # 
    # for i in range(0,len(items)):
    #   print items[i]
    # for i in range(0,len(M)):
    #   print M[i]
    M, optimal_value = generate_optimal_solutions(items, len(items), capacity)
    optimal_set = []
    # raise the recursion limit so that we can handle a large number of items
    #sys.setrecursionlimit(len(items)+10)
    optimal_weight = get_optimal_set(items, len(items), M, len(items)-1, capacity, optimal_set, 0)
    
    return optimal_set, optimal_weight, optimal_value



In [65]:
def generate_optimal_solutions(items, n, capacity):
    M = [[]]
    for w in range(0,capacity+1):
      M[0].append(0) # = 0

    for i in range(0,n):
      M.append([])
      for w in range(0,capacity+1):
        if (items[i][0] > w):
          M[i+1].append(M[i-1+1][w])
        else:
          M[i+1].append( max(M[i-1+1][w], items[i][1] + M[i-1+1][w - items[i][0]]) )

    return M, M[n][capacity]
  

In [66]:
def get_optimal_set(items, n, M, j, w, optimal_set, optimal_weight):
    print(items[j][0])
    print(items[j][1])
    print(M[j-1+1][w - items[j][0]])
    print(M[j-1+1][w])
    if (j < 0):
      pass
    elif (w >= items[j][0] and items[j][1] + M[j-1+1][w - items[j][0]] > M[j-1+1][w]):
      optimal_set.append(items[j])
      optimal_weight += items[j][0]
      optimal_weight = get_optimal_set(items, n, M, j-1, w - items[j][0], optimal_set, optimal_weight)
    else:
      optimal_weight = get_optimal_set(items, n, M, j-1, w, optimal_set, optimal_weight)
      
    return optimal_weight

In [67]:
c = 30
n = 10
items = ((np.random.rand(n,2) + 0.1) * 10).astype(int)
print(items)
m = np.zeros((n+1, c+1))
print(m.shape)
optimal_set = []

[[ 9  3]
 [ 9  5]
 [ 2  4]
 [ 4  9]
 [ 1  6]
 [ 3  6]
 [ 9  5]
 [ 5  1]
 [10  4]
 [10  3]]
(11, 31)


In [69]:
solution, w, v = solve(items, c)
if solution != []:
    
    print("solution of weight %d, value %d found:" % (w,v))
    print(", ".join(map(lambda t: str(t), solution)))
else:
    # this should never happen (and hasen't as far as we're concerned)
    print('no solution found(!).')

10
3
30
35
10
4
30
35
5
1
30
35
9
5
30
33
3
6
24
24
1
6
18
18
4
9
9
9
2
4
5
5
9
5
0
3
9
3
0
0
10
3
30
6
solution of weight 28, value 35 found:
[9 5], [3 6], [1 6], [4 9], [2 4], [9 5]
