In [1]:
import numpy as np


In [2]:
file = open("example.in", "r") 
text = file.read()

In [3]:
header_id = text.index('\n')
# Get header
header = text[0:header_id].split(' ')
row =  int(header[0])
col =  int(header[1])
pmin = int(header[2])
pmax = int(header[3])
# Get body
body = text[header_id:]
body = body.replace('T','0 ').replace('M','1 ').replace('\n','')
body = np.fromstring(body, dtype=int, sep=' ')
body = np.reshape(body, (row,col))

In [4]:
# Print resume
print('row=' + str(row), 'col=' + str(col), 'pmin=' + str(pmin), 'pmax='+ str(pmax))
print('body:\n', body)

row=3 col=5 pmin=1 pmax=6
body:
 [[0 0 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
